"""Current production "order status" report. Do NOT edit this file — it's
the buggy script Support says is showing wrong statuses to customers. Your
fix goes in dedupe.py instead.

Usage: python starter/naive_report.py
"""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATASET = ROOT / "datasets" / "order_events.csv"


def main():
    with open(DATASET, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    order_ids = [r["order_id"] for r in rows]
    print(f"total event rows: {len(rows)}")
    print(f"distinct order_id: {len(set(order_ids))}")

    status_by_order = {}
    for row in rows:
        status_by_order[row["order_id"]] = row["status"]  # last row in the file wins

    print("\ncurrent status per order (naive: last row in the file wins):")
    for order_id in sorted(status_by_order):
        print(f"  {order_id}: {status_by_order[order_id]}")


if __name__ == "__main__":
    main()
